### ISSUE TITLE
Limit language selection

### ISSUE THREAD

**Issue by mrchrmn** [alexandria-reader/frontend#108]
Should we limit our language selection to those where every possible pair has a Word Reference link?

**Comment by eamon0989** [comment]
Yes, for now that is a great idea. I would also limit them to languages that one of use is at least familiar with.

**Comment by mrchrmn** [comment]
There is a mismatch on Word Reference between languages translating to and from English and to and from other languages. 

Maybe this is the time to fill our `webdicitionaries` table with valid Word Reference links? If a language pair doesn't exist in that table, we offer the English version as a backup. This way we won't stop a Dane from learning Czech, but they would have to make do with the Czeck->English dictionary.
