### ISSUE TITLE
When clicking the settings link, the navbar flashes, briefly showing the login and signup buttons

### ISSUE THREAD

**Issue by eamon0989** [alexandria-reader/frontend#122]

**Comment by eamon0989** [comment]
When clicking settings (on desktop and on mobile) the navbar flashes, briefly showing the login and signup buttons.

After briefly investigating it, it seems that the `user` is not defined in recoil for some reason meaning that it shows the logged out navbar. Once the user is "found", the normal navbar is displayed.

**Comment by eamon0989** [comment]
Turns out the delay is caused because an api call is being made to check the user associated with the token, and until the response is recieved, the user doesn't exist.

**Comment by eamon0989** [comment]
It appears that the recoil state `userState` does not persist, and clicking on the settings menu forces `app.tsx` to  make an API call to get the user from the token. @mrchrmn Can you take a look at it when you get a chance as you set up the `userState`?

**Comment by mrchrmn** [comment]
This was not a bug, and not an issue with the settings page. It turned out that `settings` was a regular `href` link in the NavBar, not a `NavLink`. I fixed that (I hope) in `Nav.tsx` and will issue a pull request for it now.
