### ISSUE TITLE
Adding a new translation to an existing word and going to the vocabulary page crashes the app with the message below.

### ISSUE THREAD

**Issue by eamon0989** [alexandria-reader/frontend#123]
react_devtools_backend.js:4045 TypeError: First argument must be a string
    at l (index.js:19:11)
    at Words.tsx:98:79
    at Array.map (<anonymous>)
    at Words.tsx:97:48
    at Array.map (<anonymous>)
    at ed (Words.tsx:81:30)
    at li (react-dom.production.min.js:157:137)
    at Ql (react-dom.production.min.js:267:460)
    at Lu (react-dom.production.min.js:250:347)
    at Tu (react-dom.production.min.js:250:278)
overrideMethod @ react_devtools_backend.js:4045
cl @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
mo @ react-dom.production.min.js:131
gl @ react-dom.production.min.js:220
Ru @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
$a @ react-dom.production.min.js:122
Ou @ react-dom.production.min.js:252
bu @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$a @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Qa @ react-dom.production.min.js:122
Pe @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
index.js:19 Uncaught TypeError: First argument must be a string
    at l (index.js:19:11)
    at Words.tsx:98:79
    at Array.map (<anonymous>)
    at Words.tsx:97:48
    at Array.map (<anonymous>)
    at ed (Words.tsx:81:30)
    at li (react-dom.production.min.js:157:137)
    at Ql (react-dom.production.min.js:267:460)
    at Lu (react-dom.production.min.js:250:347)
    at Tu (react-dom.production.min.js:250:278)

**Comment by mrchrmn** [comment]
The reason for this error is that not context is set for the additional translation, not even an empty string. I will try to quick-fix this in the words table but the problem seems to lie in the `TranslationInput` component.

**Comment by eamon0989** [comment]
Perfect I'll take a look at that, thanks!

**Comment by mrchrmn** [comment]
It seems that while this is always the reason for the error (`translation.context` is `undefined`) I cannot put my finger on exactly where it comes from. Maybe it is about adding a new translation to a phrase, not a word? In any case, If anything goes wrong with the context, the table will handle it.
