### ISSUE TITLE
Phrase selection on android doesn't work correctly

### ISSUE THREAD

**Issue by eamon0989** [alexandria-reader/frontend#134]
After selection the text, you have to tap somewhere on the screen for the modal to open.

**Comment by eamon0989** [comment]
Unfortunately I’m going to leave this one for now, it’s taken up too much time already. Currently the best way to get a phrase on android is long press and drag, then tap on the selection to open the phrase. Once the rest of the app is finishing I can look into this again.

**Comment by mrchrmn** [comment]
This works good enough. I'm closing this.
