### ISSUE TITLE
On mobile, clicking the hamburger menu and then clicking the settings menu should close the hamburger menu

### ISSUE THREAD

**Issue by eamon0989** [alexandria-reader/frontend#154]

**Comment by mrchrmn** [comment]
Speaking of the hamburger and mobile view:
Would it be possible (and better) to
- get rid of the user pull down
- include settings and sign out into the hamburger menu
- move the menu to the right (better to access one-handed)
- move the logo to the left (like in logged out navbar)
?

**Comment by eamon0989** [comment]
Good idea, I'll do that today 👍🏼
