### ISSUE TITLE
Fallback component while loading texts should be white or wireframe

### ISSUE THREAD

**Issue by mrchrmn** [alexandria-reader/frontend#182]
Right now, while a text is being loaded, the 404 appears while an existing text is being loaded. It should only be displayed if there is an actual 404 coming from the server.

**Comment by eamon0989** [comment]
Something like this would be great, I've looked into it but I don't have any experience with SVG files.

https://skeletonreact.com/

**Comment by mrchrmn** [comment]
I can create loading SVGs to resemble texts list and text page. I just don't know where to put them.

**Comment by eamon0989** [comment]
If you make them, I can add them

**Comment by mrchrmn** [comment]
This still needs one more fix on the text list page.
