### ISSUE TITLE
Going to tryalexandria shows this:

### ISSUE THREAD

**Issue by eamon0989** [alexandria-reader/frontend#229]
<img width="1440" alt="Screen Shot 2022-01-15 at 11 45 10" src="https://user-images.githubusercontent.com/21305201/149618948-c946ecbb-fb6c-4002-97d3-0a73c718f125.png">
<img width="1440" alt="Screen Shot 2022-01-15 at 11 48 05" src="https://user-images.githubusercontent.com/21305201/149619017-a0912217-d54e-452a-89b0-ababd978d394.png">

**Comment by eamon0989** [comment]
It was an old user token for a user that had been deleted. But this shouldn't happen, a user should always be taken to the front page even if there is a problem with a user token.

**Comment by mrchrmn** [comment]
Our whole app is frighteningly devoid of try-catches.
