### ISSUE TITLE
We need separate Userword states for vocabulary and curren text

### ISSUE THREAD

**Issue by mrchrmn** [alexandria-reader/frontend#260]
otherwise highlights from vocabulary not belonging to the known language settings flash in the text.

**Comment by eamon0989** [comment]
Interesting, I haven't seen this. How did you reproduce the bug?

**Comment by mrchrmn** [comment]
It is a flaw in the design. The vocabulary holds all the words of the learn language, independent of the known language. Some translations might be English->German, others English->French. All collected in the Userwords state. When you then switch to a text, all Userwords are briefly highlighted, then, a flicker later, only the ones of the known language remain. 

Conversly, when you go from text to vocabulary, you briefly see just the words from the text, then all others are there. 

The first case is probably unlikely, because most people won't switch their known language, will they? But if they do, it looks buggy.

**Comment by eamon0989** [comment]
I see what you mean. We could fix this easily enough (I think) by filtering the user words by current language, either on the backend or when they are recieved on the frontend. When the user changes the known language, we would have to do an API call and get the user words again to filter them (or have them filtered on the backend).

**Comment by mrchrmn** [comment]
That is exactly what we are doing right now. But while we are waiting for the API call to go through, the Userwords state has not changed and is displayed for that brief moment.

**Comment by mrchrmn** [comment]
I'll look into clearing the Userwords immediately when switching to the page.

**Comment by eamon0989** [comment]
I don't think that is what currently happens. Right now, in UserTexts, an API call is made which returns all of the user words in their learn language (e.g. French). But they are never filtered by the known language. We can simply filter them by known language, and then fetch the words again if the known language changes.

**Comment by mrchrmn** [comment]
Ah, I see what happened and when it started: I never fetched any userwords on the texts list. You introduced this to fill  the stats. I think a `getStats` service would be better for that purpose because there is no point for full userwords to be loaded at this point. 

Anyway, the text page currently fetches userwords that belong to the text from the server, The vocabulary does what you did on the text list: it loads all userwords in the learn language. 

Each page makes its own userwords API call, but single text and vocabulary and text list, need different data. It should not be kept in the same state.

**Comment by mrchrmn** [comment]
I would like to refactor this.

**Comment by eamon0989** [comment]
Sounds good 👍🏼

**Comment by eamon0989** [comment]
It might be worth adding a few unit tests first if possible to prevent regression as it will be hard to test every possible scenario manually.

**Comment by mrchrmn** [comment]
What would be the units to test? The services?

**Comment by eamon0989** [comment]
Idealy we would test whatever we are going to refactor. So in this case, user words, user words in current text and the stats?
