### ISSUE TITLE
Cannot set known and learn language from the navbar anymore.

### ISSUE THREAD

**Issue by mrchrmn** [alexandria-reader/frontend#71]
What is the language that I can select from the navbar? I would assume it is the current learn language. But where can I change my known language (the one I translate to)?

**Comment by eamon0989** [comment]
Now the navbar allows you to change the language you are learning. It doesn't allow you to learn a "known" language or to choose the language you are already learning. We need to add the option to change "known" languages through the settings/user profile, as it is a setting most people will never change.

**Comment by mrchrmn** [comment]
That's correct. The navbar setting should still be labelled more clearly: "I am learning...". 

I needed the known language setting just now to track weird behaviour with userwords. That's when I realised I cannot change it anymore.

**Comment by eamon0989** [comment]
I disagree, I think "I am learning" would be too verbose. If you look at lingq they do it the way we have it now. Button name is the current "learn" language, clicking the button shows all possible learn languages.

**Comment by mrchrmn** [comment]
They make it clearer by having a mouse-over tooltip "You know 108 French words", though. And the number. 
We could have something like
Learn :de:
|-- German :de:
|-- French :fr:

**Comment by eamon0989** [comment]
In my opinion just having the flag and language is a lot cleaner. And we can always add the word count as a future enhancement. We could even add a tooltip now if necessary.
