### ISSUE TITLE
Language mismatches

### ISSUE THREAD

**Issue by mrchrmn** [alexandria-reader/frontend#72]
Translation target languages are currently set to learn language, but should be known language. 
I will go through all of the current `main` code to double check that we're always using the correct language (ie. known or learn) and make the appropriate changes.

**Comment by eamon0989** [comment]
Where did you see this? Can you link to the code?

**Comment by mrchrmn** [comment]
From `TranslationInput.tsx`:
~~~js
const translationObj: Translation = {
  translation,
  targetLanguageId: currentUserLanguages?.currentLearnLanguageId,
  context: '',
};
~~~
https://github.com/alexandria-reader/frontend/blob/62d35413211ddaf74074667f61ca8369be2da746/src/components/texts/TranslationInput.tsx#L57
