### ISSUE TITLE
Some characters such as  « are not wrapped in a span

### ISSUE THREAD

**Issue by eamon0989** [alexandria-reader/frontend#94]

**Comment by mrchrmn** [comment]
Not a bug. I deliberately changed the code a while back to only wrap words and phrases, to uncluttered the DOM. Is that a problem?

**Comment by eamon0989** [comment]
It may be a problem for the new way that selection works. Let me keep working selection for now and if it's still a problem I'll let you know at the meeting later.

**Comment by mrchrmn** [comment]
I think, you have already gone back to putting punctuation into spans in the latest updates, right?
